"""Privileged replay records and deterministic reconstruction.

Specification sources:

- `03_game_engine_spec.md` section 12
- `09_public_event_and_replay_schema.md` sections 3, 13, 18
- `07_observation_validation_matrix.md` section 12

Stratego contains no random combat outcome, so the two true setups plus the
ordered action sequence fully determine every later state. The record also
carries the seeds that produced any stochastic input, so a game generated by the
random testing agent can be regenerated as well as replayed.
"""

import json
from dataclasses import asdict, dataclass, field

from .constants import (
    EVENT_SCHEMA_VERSION,
    OBSERVATION_VERSION,
    PLAYER_BY_NAME,
    PLAYER_NAMES,
    REPLAY_VERSION,
    RulesConfig,
)
from .setup import deserialize_setup, serialize_setup
from .state import GameState, create_game
from .transition import apply_action


@dataclass
class ReplayRecord:
    """Minimal authoritative replay record (`09_...` section 3)."""

    replay_version: str
    rules_version: str
    observation_version: str
    event_schema_version: str
    game_id: str
    red_setup: str
    blue_setup: str
    first_player: str
    battleless_move_limit: int
    absolute_move_limit: int
    rules_context: str
    actions: list[int]
    terminal_result: str
    terminal_reason: str
    total_moves: int
    # Explicit seeds for any stochastic input, so a generated game can be
    # reproduced from the record alone rather than only replayed.
    seeds: dict = field(default_factory=dict)

    def to_json(self) -> str:
        return json.dumps(asdict(self), separators=(",", ":"), sort_keys=True)

    @staticmethod
    def from_json(text: str) -> "ReplayRecord":
        return ReplayRecord(**json.loads(text))


def rules_from_record(record: ReplayRecord) -> RulesConfig:
    """Rebuild the exact rules configuration a record was played under."""
    return RulesConfig(
        rules_version=record.rules_version,
        first_player=PLAYER_BY_NAME[record.first_player],
        battleless_move_limit=record.battleless_move_limit,
        absolute_move_limit=record.absolute_move_limit,
        context=record.rules_context,
    )


def terminal_result_label(state: GameState) -> str:
    """`red_win`, `blue_win` or `draw` for a finished game."""
    if not state.terminal:
        return "unfinished"
    if state.winner is None:
        return "draw"
    return f"{PLAYER_NAMES[state.winner]}_win"


def build_replay_record(
    state: GameState,
    red_setup: "tuple[int, ...]",
    blue_setup: "tuple[int, ...]",
    seeds: dict | None = None,
) -> ReplayRecord:
    """Create a replay record from a played-out game state."""
    return ReplayRecord(
        replay_version=REPLAY_VERSION,
        rules_version=state.rules.rules_version,
        observation_version=OBSERVATION_VERSION,
        event_schema_version=EVENT_SCHEMA_VERSION,
        game_id=state.game_id,
        red_setup=serialize_setup(red_setup),
        blue_setup=serialize_setup(blue_setup),
        first_player=PLAYER_NAMES[state.rules.first_player],
        battleless_move_limit=state.rules.battleless_move_limit,
        absolute_move_limit=state.rules.absolute_move_limit,
        rules_context=state.rules.context,
        actions=list(state.action_history),
        terminal_result=terminal_result_label(state),
        terminal_reason=state.terminal_reason,
        total_moves=state.total_moves,
        seeds=dict(seeds or {}),
    )


def initial_state_from_record(record: ReplayRecord) -> GameState:
    """Rebuild the position before the first action."""
    return create_game(
        deserialize_setup(record.red_setup),
        deserialize_setup(record.blue_setup),
        rules=rules_from_record(record),
        game_id=record.game_id,
    )


def replay_plies(record: ReplayRecord):
    """Yield `(ply_index, state, events)` for the start position and each action.

    The same mutable state object is yielded each time, so a consumer that needs
    to keep a ply must copy or hash it immediately. Yielding in place is what
    makes replaying thousands of games affordable.
    """
    state = initial_state_from_record(record)
    yield 0, state, []
    for index, action_id in enumerate(record.actions, start=1):
        events = apply_action(state, action_id)
        yield index, state, events


def rebuild_final_state(record: ReplayRecord) -> GameState:
    """Replay a record to completion and return the final state."""
    state = initial_state_from_record(record)
    for action_id in record.actions:
        apply_action(state, action_id)
    return state
